version: '3.1'

services:
  api_service:
    container_name: api_service
    build:
      context: .
    volumes:
      - static_volume:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    env_file:
      - .env
    restart: always

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: hello
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  pgdata:
  static_volume: