version: '3.1'

services:
  api_service:
    container_name: api_service
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on:
      - api_service

  adminer:
    image: adminer
    restart: always
    ports:
      - "7500:8080"
    depends_on:
      - pgdb

volumes:
  pgdata: